name: Generate Instagram Post

on:
  schedule:
    - cron: '0 15 * * *'  # 11 AM EST daily
  workflow_dispatch:

jobs:
  generate-instagram:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: |
          cd tools/ig-generator
          npm install
      
      - name: Generate post
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ZAPIER_WEBHOOK_URL: ${{ secrets.ZAPIER_WEBHOOK_URL }}
        run: |
          cd tools/ig-generator
          node generate-single-post.js
      
      - name: Upload post
        uses: actions/upload-artifact@v4
        with:
          name: instagram-post-${{ github.run_number }}
          path: tools/ig-generator/drafts/
          retention-days: 30
      
      - name: Commit to repo
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add tools/ig-generator/drafts/
          git commit -m "Generated Instagram post - $(date)" || echo "No changes"
          git push
